services:
  - docker

install:
  - docker build -t locust:latest .
  - docker build -t locust:python2 ./python2
  - docker run -d -p 8089:8089 locust:latest
  - docker run -d -p 8090:8089 locust:python2

script:
  - sleep 5
  - docker ps | grep -q locust:latest
  - docker ps | grep -q locust:python2
