services:
  - docker

env:
  global:
    - RELEASE_VERSION=1.2

install:
  - docker build -t locust:latest ./$RELEASE_VERSION
  - docker build -t locust:python2 ./$RELEASE_VERSION/python2
  - docker run -d -p 8089:8089 locust:latest
  - docker run -d -p 8090:8089 locust:python2

script:
  - sleep 5
  - docker ps | grep -q locust:latest
  - docker ps | grep -q locust:python2
