version: 2.1
aliases:
  - &build_steps
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:$IMAGE_TAG $DOCKERFILE_PATH --label "org.opencontainers.image.version=${CIRCLE_TAG/v/''}"
      - run:
          name: Cache Docker image
          command: docker save -o $IMAGE_TAG.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./*.tar
executors:
  docker-executor:
    environment:
      IMAGE_NAME: peterevans/locust
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-executor
    environment:
      IMAGE_TAG: latest
      DOCKERFILE_PATH: .
    <<: *build_steps
  build-python2:
    executor: docker-executor
    environment:
      IMAGE_TAG: python2
      DOCKERFILE_PATH: ./python2
    <<: *build_steps
  test:
    executor: docker-executor
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load cached Docker image
          command: |
            docker load -i /tmp/workspace/latest.tar
            docker load -i /tmp/workspace/python2.tar
      - run:
          name: Test Docker image
          command: |
            docker run -d $IMAGE_NAME:latest
            docker run -d $IMAGE_NAME:python2
            sleep 5
            docker ps | grep -q $IMAGE_NAME:latest
            docker ps | grep -q $IMAGE_NAME:python2
  publish-tag:
    executor: docker-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load cached Docker image
          command: |
            docker load -i /tmp/workspace/latest.tar
            docker load -i /tmp/workspace/python2.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            IMAGE_TAG=${CIRCLE_TAG/v/''}
            docker tag $IMAGE_NAME:python2 $IMAGE_NAME:$IMAGE_TAG-python2
            docker push $IMAGE_NAME:python2
            docker push $IMAGE_NAME:$IMAGE_TAG-python2
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$IMAGE_TAG
            # If the minor version can be extracted then tag and push
            MINOR_VERSION=$(echo $CIRCLE_TAG | sed -n "s/^v\([0-9]*.[0-9]*\).[0-9]*$/\1/p")
            if [[ ${#MINOR_VERSION} -gt 0 ]]; then
              docker tag $IMAGE_NAME:python2 $IMAGE_NAME:$MINOR_VERSION-python2
              docker push $IMAGE_NAME:$MINOR_VERSION-python2            
              docker tag $IMAGE_NAME:latest $IMAGE_NAME:$MINOR_VERSION
              docker push $IMAGE_NAME:$MINOR_VERSION
            fi
workflows:
  version: 2
  build:
    jobs:
      - build
      - build-python2
      - test:
          requires:
            - build
            - build-python2
  build-and-publish-tags:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-python2:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - test:
          requires:
            - build
            - build-python2
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish-tag:
          context: org-global
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/