apiVersion: v1
kind: Service
metadata:
  name: locust-master
  labels:
    name: locust-master
spec:
  type: LoadBalancer
  selector:
    name: locust-master
    role: master
  ports:
    - port: 8089
      protocol: TCP
      name: master-web
    - port: 5557
      protocol: TCP
      name: master-port1
    - port: 5558
      protocol: TCP
      name: master-port2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
spec:
  replicas: 1
  selector:
    matchLabels:
      name: locust-master
  template:
    metadata:
      labels:
        name: locust-master
        role: master
    spec:
      volumes:
        - name: locust-volume
          configMap:
            name: locust-configmap
      containers:
        - name: locust
          image: locustio/locust:1.1.1
          env:
            - name: LOCUST_TARGET_HOST
              value: "https://api.nexon.co.kr"
          volumeMounts:
            - name: locust-volume
              mountPath: /locust-tasks
          args:
            [
              "--master",
              "--host",
              "$LOCUST_TARGET_HOST",
              "-f",
              "/locust-tasks/basic.py",
            ]
          command: ["locust"]
          ports:
            - containerPort: 8089
            - containerPort: 5557
            - containerPort: 5558
